[package]
name = "cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrussh = "0.33.5"
thrussh-keys = "0.21.0"
tokio = "1.17.0"
futures = "0.3.21"
env_logger = "0.9.0"
anyhow = "1.0.55"
